#!/usr/bin/env python3
"""Generate README terminal screenshots from real Proofpress CLI output."""

from __future__ import annotations

import argparse
import html
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "portable-handoff"
OUTPUT = ROOT / "assets" / "quickstart"
CLI = ROOT / "proofpress.py"
ANSI = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")


def run(cwd: Path, *args: str) -> str:
    env = dict(os.environ)
    env["NO_COLOR"] = "1"
    result = subprocess.run(
        [sys.executable, str(CLI), *args],
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
    )
    output = ANSI.sub("", result.stdout + result.stderr).rstrip()
    if result.returncode:
        raise RuntimeError(
            f"proofpress {' '.join(args)} failed ({result.returncode}):\n{output}"
        )
    prompt = f"$ proofpress {' '.join(args)}"
    return f"{prompt}\n{output}" if output else prompt


def render_svg(title: str, transcript: str) -> str:
    lines = transcript.splitlines()
    width = 1120
    line_height = 20
    top = 62
    height = top + max(1, len(lines)) * line_height + 24
    spans = []
    for index, line in enumerate(lines):
        css_class = "prompt" if line.startswith("$ ") else "output"
        y = top + index * line_height
        spans.append(
            f'  <text class="{css_class}" x="24" y="{y}">{html.escape(line)}</text>'
        )
    body = "\n".join(spans)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">
  <title id="title">{html.escape(title)}</title>
  <desc id="desc">Terminal output generated by the Proofpress quickstart.</desc>
  <rect width="{width}" height="{height}" rx="12" fill="#0d1117"/>
  <rect width="{width}" height="38" rx="12" fill="#161b22"/>
  <path d="M0 26h{width}v12H0z" fill="#161b22"/>
  <circle cx="22" cy="19" r="5" fill="#ff7b72"/>
  <circle cx="40" cy="19" r="5" fill="#d29922"/>
  <circle cx="58" cy="19" r="5" fill="#3fb950"/>
  <style>
    text {{ font: 14px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace; white-space: pre; }}
    .prompt {{ fill: #79c0ff; }}
    .output {{ fill: #e6edf3; }}
  </style>
{body}
</svg>
"""


def transcripts() -> dict[str, tuple[str, str]]:
    with tempfile.TemporaryDirectory(prefix="proofpress-quickstart-") as raw:
        demo = Path(raw)
        subprocess.run(
            ["git", "init", "-q"], cwd=demo, check=True, capture_output=True
        )
        for name in ("strategy.md", "proposal.docx", "proposal.provenance.json"):
            shutil.copy2(EXAMPLE / name, demo / name)

        inspect = run(demo, "inspect", "strategy.md")
        imported = run(demo, "import", "strategy.md")
        log = run(demo, "log", "strategy.md")
        diff = run(demo, "diff", "strategy.md")
        verify = run(demo, "verify", "strategy.md")
        provenance = run(
            demo,
            "provenance",
            "verify",
            "proposal.docx",
            "--evidence",
            "proposal.provenance.json",
        )

    return {
        "native-history.svg": (
            "Inspect and import portable Proofpress history",
            "\n\n".join((inspect, imported, log)),
        ),
        "native-diff-verify.svg": (
            "Review and verify an admitted Proofpress revision",
            "\n\n".join((diff, verify)),
        ),
        "docx-provenance.svg": (
            "Verify semantic evidence for a DOCX artifact",
            provenance,
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed screenshots differ from current CLI output",
    )
    args = parser.parse_args()

    expected = {
        filename: render_svg(title, transcript)
        for filename, (title, transcript) in transcripts().items()
    }
    stale = []
    for filename, payload in expected.items():
        path = OUTPUT / filename
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != payload:
                stale.append(path.relative_to(ROOT))
        else:
            OUTPUT.mkdir(parents=True, exist_ok=True)
            path.write_text(payload, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        for path in stale:
            print(f"stale quickstart screenshot: {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
