#!/usr/bin/env python3
"""Generate README terminal screenshots from real Proofpress CLI output."""

from __future__ import annotations

import argparse
import errno
import fcntl
import html
import math
import os
from pathlib import Path
import pty
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import termios


ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "portable-handoff"
OUTPUT = ROOT / "assets" / "quickstart"
CLI = ROOT / "proofpress.py"
ANSI = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
SGR = re.compile(r"\x1b\[([0-9;]*)m")
MIN_WIDTH = 1120
HORIZONTAL_PADDING = 48
CHAR_WIDTH = 8.45


def tty_output(cwd: Path, *args: str) -> tuple[int, str]:
    """Run the CLI in a fixed-size pseudo-terminal so its real colors render."""
    env = dict(os.environ)
    env.pop("NO_COLOR", None)
    master, slave = pty.openpty()
    fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 160, 0, 0))
    process = subprocess.Popen(
        [sys.executable, str(CLI), *args],
        cwd=cwd,
        env=env,
        stdin=subprocess.DEVNULL,
        stdout=slave,
        stderr=slave,
    )
    os.close(slave)
    chunks = []
    try:
        while True:
            try:
                chunk = os.read(master, 4096)
            except OSError as exc:
                if exc.errno == errno.EIO:
                    break
                raise
            if not chunk:
                break
            chunks.append(chunk)
    finally:
        os.close(master)
    return process.wait(), b"".join(chunks).decode("utf-8", errors="replace")


def run(cwd: Path, *args: str) -> str:
    returncode, output = tty_output(cwd, *args)
    output = output.replace("\r\n", "\n").replace("\r", "\n").rstrip()
    if returncode:
        raise RuntimeError(
            f"proofpress {' '.join(args)} failed ({returncode}):\n"
            f"{ANSI.sub('', output)}"
        )
    prompt = f"$ proofpress {' '.join(args)}"
    return f"{prompt}\n{output}" if output else prompt


def ansi_svg(line: str) -> str:
    """Translate the CLI's SGR colors and emphasis into SVG tspans."""
    output = []
    position = 0
    color = None
    bold = False
    strike = False
    for match in SGR.finditer(line):
        text = line[position : match.start()]
        if text:
            attrs = []
            if color:
                attrs.append(f'fill="{color}"')
            if bold:
                attrs.append('font-weight="700"')
            if strike:
                attrs.append('text-decoration="line-through"')
            escaped = html.escape(text)
            output.append(
                f"<tspan {' '.join(attrs)}>{escaped}</tspan>" if attrs else escaped
            )
        codes = [int(code) for code in match.group(1).split(";") if code]
        if not codes or 0 in codes:
            color = None
            bold = False
            strike = False
        if 1 in codes:
            bold = True
        if 9 in codes:
            strike = True
        if len(codes) >= 5 and codes[:2] == [38, 2]:
            color = f"#{codes[2]:02X}{codes[3]:02X}{codes[4]:02X}"
        position = match.end()
    tail = line[position:]
    if tail:
        attrs = []
        if color:
            attrs.append(f'fill="{color}"')
        if bold:
            attrs.append('font-weight="700"')
        if strike:
            attrs.append('text-decoration="line-through"')
        escaped = html.escape(tail)
        output.append(
            f"<tspan {' '.join(attrs)}>{escaped}</tspan>" if attrs else escaped
        )
    return "".join(output)


def render_svg(title: str, transcript: str, width: int) -> str:
    lines = transcript.splitlines()
    line_height = 20
    top = 62
    height = top + max(1, len(lines)) * line_height + 24
    spans = []
    for index, line in enumerate(lines):
        css_class = "prompt" if line.startswith("$ ") else "output"
        y = top + index * line_height
        spans.append(
            f'  <text class="{css_class}" x="24" y="{y}">{ansi_svg(line)}</text>'
        )
    body = "\n".join(spans)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">
  <title id="title">{html.escape(title)}</title>
  <desc id="desc">Terminal output generated by the Proofpress quickstart.</desc>
  <rect width="{width}" height="{height}" rx="12" fill="#0d1117"/>
  <rect width="{width}" height="38" rx="12" fill="#161b22"/>
  <path d="M0 26h{width}v12H0z" fill="#161b22"/>
  <circle cx="22" cy="19" r="5" fill="#ff7b72"/>
  <circle cx="40" cy="19" r="5" fill="#d29922"/>
  <circle cx="58" cy="19" r="5" fill="#3fb950"/>
  <style>
    text {{ font: 14px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace; white-space: pre; }}
    .prompt {{ fill: #79c0ff; }}
    .output {{ fill: #e6edf3; }}
  </style>
{body}
</svg>
"""


def transcripts() -> dict[str, tuple[str, str]]:
    with tempfile.TemporaryDirectory(prefix="proofpress-quickstart-") as raw:
        demo = Path(raw)
        subprocess.run(
            ["git", "init", "-q"], cwd=demo, check=True, capture_output=True
        )
        subprocess.run(
            ["git", "config", "user.name", "Proofpress Quickstart"],
            cwd=demo,
            check=True,
        )
        subprocess.run(
            ["git", "config", "user.email", "quickstart@example.invalid"],
            cwd=demo,
            check=True,
        )
        for name in ("strategy.md", "proposal.docx", "proposal.provenance.json"):
            shutil.copy2(EXAMPLE / name, demo / name)

        inspect = run(demo, "inspect", "strategy.md")
        imported = run(demo, "import", "strategy.md")
        log = run(demo, "log", "strategy.md")
        diff = run(demo, "diff", "strategy.md")
        verify = run(demo, "verify", "strategy.md")
        provenance = run(
            demo,
            "provenance",
            "verify",
            "proposal.docx",
            "--evidence",
            "proposal.provenance.json",
        )

    return {
        "native-history.svg": (
            "Inspect and import portable Proofpress history",
            "\n\n".join((inspect, imported, log)),
        ),
        "native-diff-verify.svg": (
            "Review and verify an admitted Proofpress revision",
            "\n\n".join((diff, verify)),
        ),
        "docx-provenance.svg": (
            "Verify semantic evidence for a DOCX artifact",
            provenance,
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed screenshots differ from current CLI output",
    )
    args = parser.parse_args()

    captured = transcripts()
    longest_line = max(
        len(ANSI.sub("", line))
        for _, transcript in captured.values()
        for line in transcript.splitlines()
    )
    width = max(
        MIN_WIDTH,
        HORIZONTAL_PADDING + math.ceil(longest_line * CHAR_WIDTH),
    )
    expected = {
        filename: render_svg(title, transcript, width)
        for filename, (title, transcript) in captured.items()
    }
    stale = []
    for filename, payload in expected.items():
        path = OUTPUT / filename
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != payload:
                stale.append(path.relative_to(ROOT))
        else:
            OUTPUT.mkdir(parents=True, exist_ok=True)
            path.write_text(payload, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        for path in stale:
            print(f"stale quickstart screenshot: {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
